### PR TITLE
Fix everySecond bug

### LINKED ISSUE #54: swift run Run jobs --scheduled only works with using .at()
If you schedule a job using at with a specific date then the scheduled works.. however if you try and setup a job using something like `.everySecond()` it never process the jobs

works
```
public func configure(_ app: Application) throws {
    app.jobs.schedule(TestJob()).at(Date(rfc1123: "Sat, 04 Jan 2020 16:47:40 GMT")!)
    try app.jobs.use(.redis(url: "redis://127.0.0.1:6379"))
}
```

Doesn't work
```
public func configure(_ app: Application) throws {
    app.jobs.schedule(TestJob()).everySecond()
    try app.jobs.use(.redis(url: "redis://127.0.0.1:6379"))
}
```

job is just a simple print
```
struct TestJob: ScheduledJob {    
    func run(context: JobContext) -> EventLoopFuture<Void> {
        print("Job has run \(context)")       
        return context.eventLoop.makeSucceededFuture(Void())
    }
}
```
if I make the change to ScheduleBuilder:
```
    public func everySecond() {
        self.second = 1
    }
```

and put in a breakpoint in the `nextDate(current` function I can get it to run once.. but not repeated

### PR DESCRIPTION
**Pull request by mcdappdev**
This update fixes a bug that caused `everySecond()` not to fire when running scheduled jobs.

### CODE REVIEW

File: Tests/JobsTests/JobsTests.swift [hunk 1]
```diff
@@ -78,6 +78,32 @@ final class JobsTests: XCTestCase {
             .hourly()
             .at(30)
     }
+    
+    func testRepeatingScheduledJob() throws {
+        let app = Application(.testing)
+        defer { app.shutdown() }
+        
+        XCTAssertEqual(TestingScheduledJob.count, 0)
+        app.jobs.schedule(TestingScheduledJob()).everySecond()
```
Comment (tanner0101) [inline Tests/JobsTests/JobsTests.swift]: This should be producing a warning, right?

Comment (mcdappdev) [reply Tests/JobsTests/JobsTests.swift]: Nope. Why?

Comment (tanner0101) [reply Tests/JobsTests/JobsTests.swift]: Hmm weird, I'll look into this.

Comment (tanner0101) [reply Tests/JobsTests/JobsTests.swift]: Oh wait, this is fixed now. The PR body confused me. I understand now haha.

Comment (mcdappdev) [reply Tests/JobsTests/JobsTests.swift]: Oh ok cool! :)

Comment (Andrewangeta) [reply Tests/JobsTests/JobsTests.swift]: Is that related to this issue? 
https://github.com/apple/swift-nio/issues/1334

**Comment by Andrewangeta** [comment]
Or was that the Jobs driver specifically?

**Comment by mcdappdev** [comment]
@tanner0101 will do! 

@Andrewangeta you are thinking of https://github.com/vapor/jobs-redis-driver/issues/11

**Comment by tanner0101** [comment]
These changes are now available in [1.0.0-beta.3.2](https://github.com/vapor/jobs/releases/tag/1.0.0-beta.3.2)
